# Generated by Django 3.2.9 on 2021-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_about', models.CharField(max_length=400)),
                ('Product_price', models.IntegerField(max_length=4)),
                ('Product_date', models.DateField()),
            ],
        ),
    ]
